apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tournament-app-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: tournament-app-pipeline
  params:
    - name: image-repo
      value: quay.io/qqye/tournament
    - name: app-name
      value: tournament-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi